base_url = "https://brockman.news"
theme = "terminimal"
compile_sass = true
build_search_index = false
generate_feeds = true

[markdown]
highlight_code = true

[extra]
logo_text = "brockman"
enable_post_view_navigation = true

menu_items = [
    {name = "home", url = "$BASE_URL/about"},
    {name = "blog", url = "$BASE_URL"},
    {name = "archive", url = "$BASE_URL/archive"},
    {name = "github", url = "https://github.com/brockman.news"},
]
