name: Blog
on:
  push:
    branches:
      - master
jobs:
  build:
    name: zola
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v19
    - run: nix flake check
